const lessonTitle = "一个父亲的箴言";

const lessonData = [
    // ===== 第1段 =====
    ["孩子", "hái zi", "Child", "Anak"],
    ["，", "", "", ""],
    ["有些话", "yǒu xiē huà", "some words", "beberapa kata"],
    ["，", "", "", ""],
    ["在你长大的过程中", "zài nǐ zhǎng dà de guò chéng zhōng", "in the process of you growing up", "dalam proses awak membesar"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["要", "yào", "want to", "mahu"],
    ["和你", "hé nǐ", "with you", "dengan awak"],
    ["说说", "shuō shuo", "say", "berkata"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["昨天", "zuó tiān", "Yesterday", "Semalam"],
    ["，", "", "", ""],
    ["你回来", "nǐ huí lái", "you came back", "awak pulang"],
    ["哭哭啼啼地", "kū kū tí tí de", "crying", "sambil menangis"],
    ["告诉我", "gào su wǒ", "told me", "memberitahu saya"],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["一个同学", "yí gè tóng xué", "a classmate", "seorang rakan sekelas"],
    ["又", "yòu", "again", "lagi"],
    ["和你", "hé nǐ", "with you", "dengan awak"],
    ["闹别扭了", "nào biè niu le", "had a quarrel", "bergaduh"],
    ["，", "", "", ""],
    ["你说", "nǐ shuō", "you said", "awak berkata"],
    ["事情", "shì qing", "the matter", "perkara"],
    ["本来", "běn lái", "originally", "asalnya"],
    ["不怨你的", "bù yuàn nǐ de", "wasn't your fault", "bukan salah awak"],
    ["，", "", "", ""],
    ["是同学", "shì tóng xué", "it was the classmate", "ialah rakan sekelas"],
    ["做得太过分", "zuò de tài guò fèn", "who went too far", "yang melampau"],
    ["。", "", "", ""],
    ["爸爸", "bà ba", "Father", "Ayah"],
    ["笑了", "xiào le", "smiled", "tersenyum"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["依爸爸的经验", "yī bà ba de jīng yàn", "According to father's experience", "Menurut pengalaman ayah"],
    ["，", "", "", ""],
    ["一个人", "yí gè rén", "a person", "seseorang"],
    ["要赢得", "yào yíng dé", "to win", "untuk mendapat"],
    ["另一个人的信任", "lìng yí gè rén de xìn rèn", "another person's trust", "kepercayaan orang lain"],
    ["很容易", "hěn róng yì", "is very easy", "sangat mudah"],
    ["，", "", "", ""],
    ["那就是", "nà jiù shì", "that is", "iaitu"],
    ["要学着吃亏", "yào xué zhe chī kuī", "to learn to take the loss", "belajar untuk rugi"],
    ["。", "", "", ""],
    ["孩子", "hái zi", "Child", "Anak"],
    ["，", "", "", ""],
    ["这个世界上", "zhè ge shì jiè shàng", "in this world", "di dunia ini"],
    ["没有人", "méi yǒu rén", "no one", "tiada siapa"],
    ["喜欢", "xǐ huān", "likes", "suka"],
    ["爱占便宜的人", "ài zhàn pián yi de rén", "people who like to take advantage", "orang yang suka ambil kesempatan"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["所有人", "suǒ yǒu rén", "everyone", "semua orang"],
    ["都", "dōu", "all", "semua"],
    ["喜欢", "xǐ huān", "likes", "suka"],
    ["爱吃亏的人", "ài chī kuī de rén", "people who are willing to take losses", "orang yang sanggup rugi"],
    ["。", "", "", ""],
    ["你想着吃亏的时候", "nǐ xiǎng zhe chī kuī de shí hou", "When you are willing to take losses", "Apabila awak sanggup rugi"],
    ["，", "", "", ""],
    ["就会赢得别人", "jiù huì yíng dé bié rén", "you will win others over", "awak akan mendapat orang lain"],
    ["；", "", "", ""],
    ["那个", "nà ge", "the one", "orang yang"],
    ["懂得以更大的", "dǒng de yǐ gèng dà de", "who knows how to", "yang tahu"],
    ["吃亏方式", "chī kuī fāng shì", "take even bigger losses", "cara rugi yang lebih besar"],
    ["来回报你的人", "lái huí bào nǐ de rén", "to repay you", "untuk membalas awak"],
    ["，", "", "", ""],
    ["是你赢得的朋友", "shì nǐ yíng dé de péng yǒu", "is the friend you've won", "ialah kawan yang awak dapat"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["孩子", "hái zi", "Child", "Anak"],
    ["，", "", "", ""],
    ["人生的每一次付出", "rén shēng de měi yí cì fù chū", "Every effort in life", "Setiap pengorbanan dalam hidup"],
    ["，", "", "", ""],
    ["就像", "jiù xiàng", "is like", "seperti"],
    ["你在空谷当中的喊话", "nǐ zài kōng gǔ dāng zhōng de hǎn huà", "your shout in an empty valley", "jeritan awak di lembah kosong"],
    ["，", "", "", ""],
    ["你没有必要", "nǐ méi yǒu bì yào", "you don't need to", "awak tidak perlu"],
    ["期望", "qī wàng", "expect", "mengharapkan"],
    ["要谁听到", "yào shuí tīng dào", "anyone to hear", "sesiapa mendengar"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["那", "nà", "that", "itu"],
    ["绵长悠远的", "mián cháng yōu yuǎn de", "long and distant", "yang panjang dan jauh"],
    ["回音", "huí yīn", "echo", "gema"],
    ["，", "", "", ""],
    ["就是", "jiù shì", "is", "ialah"],
    ["生活", "shēng huó", "life", "kehidupan"],
    ["对你的", "duì nǐ de", "to you", "kepada awak"],
    ["最好回报", "zuì hǎo huí bào", "best reward", "balasan terbaik"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["你拿着", "nǐ ná zhe", "You hold", "Awak pegang"],
    ["一个", "yí gè", "a", "sebuah"],
    ["高脚的", "gāo jiǎo de", "stemmed", "berkaki tinggi"],
    ["玻璃杯", "bō li bēi", "glass", "gelas kaca"],
    ["，", "", "", ""],
    ["跳上跳下", "tiào shàng tiào xià", "jumping up and down", "meloncat-loncat"],
    ["，", "", "", ""],
    ["你要注意", "nǐ yào zhù yì", "you must be careful", "awak mesti berhati-hati"],
    ["，", "", "", ""],
    ["不要把", "bú yào bǎ", "don't", "jangan"],
    ["杯子碰碎了", "bēi zi pèng suì le", "break the glass", "memecahkan gelas"],
    ["。", "", "", ""],
    ["一个杯子", "yí gè bēi zi", "A glass", "Sebuah gelas"],
    ["，", "", "", ""],
    ["碎了以后", "suì le yǐ hòu", "once broken", "selepas pecah"],
    ["，", "", "", ""],
    ["就永远", "jiù yǒng yuǎn", "can never", "tidak akan pernah"],
    ["也不能再弥合了", "yě bù néng zài mí hé le", "be mended again", "dapat dipulihkan lagi"],
    ["，", "", "", ""],
    ["更重要的是", "gèng zhòng yào de shì", "more importantly", "yang lebih penting"],
    ["，", "", "", ""],
    ["如果", "rú guǒ", "if", "jika"],
    ["你把握不好", "nǐ bǎ wò bù hǎo", "you don't handle it well", "awak tidak kawal dengan baik"],
    ["，", "", "", ""],
    ["还会", "hái huì", "it will also", "ia juga akan"],
    ["割伤", "gē shāng", "cut", "mencederakan"],
    ["你的手指", "nǐ de shǒu zhǐ", "your fingers", "jari awak"],
    ["，", "", "", ""],
    ["让一些伤痛", "ràng yì xiē shāng tòng", "leaving some wounds", "meninggalkan beberapa luka"],
    ["永久", "yǒng jiǔ", "permanently", "selama-lamanya"],
    ["留在心里", "liú zài xīn lǐ", "in your heart", "tertinggal di hati"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["孩子", "hái zi", "Child", "Anak"],
    ["，", "", "", ""],
    ["友情", "yǒu qíng", "Friendship", "Persahabatan"],
    ["就像是", "jiù xiàng shì", "is like", "seperti"],
    ["这样一个", "zhè yàng yí gè", "such a", "begini"],
    ["精美的杯子", "jīng měi de bēi zi", "beautiful glass", "gelas yang indah"],
    ["。", "", "", ""],
    ["开始的时候", "kāi shǐ de shí hou", "At the beginning", "Pada permulaan"],
    ["，", "", "", ""],
    ["你不要", "nǐ bú yào", "you should not", "awak jangan"],
    ["被它外在的", "bèi tā wài zài de", "be fooled by its", "tertipu oleh"],
    ["光怪陆离", "guāng guài lù lí", "glittering appearance", "penampilan yang berkilau"],
    ["所迷惑", "suǒ mí huò", "outward appearance", "yang mengelirukan"],
    ["，", "", "", ""],
    ["你要", "nǐ yào", "you must", "awak mesti"],
    ["审慎地", "shěn shèn de", "carefully", "dengan berhati-hati"],
    ["去遴选和把握", "qù lín xuǎn hé bǎ wò", "select and handle", "memilih dan mengendalikan"],
    ["。", "", "", ""],
    ["再后来", "zài hòu lái", "Later on", "Kemudian"],
    ["，", "", "", ""],
    ["你对待它", "nǐ duì dài tā", "how you treat it", "cara awak memperlakukannya"],
    ["的态度", "de tài dù", "attitude", "sikap"],
    ["就非常重要了", "jiù fēi cháng zhòng yào le", "becomes very important", "menjadi sangat penting"],
    ["，", "", "", ""],
    ["一个结实的杯子", "yí gè jiē shi de bēi zi", "A sturdy glass", "Gelas yang kukuh"],
    ["，", "", "", ""],
    ["是呵护出来的", "shì hē hù chū lái de", "is nurtured", "dijaga dengan baik"],
    ["，", "", "", ""],
    ["你用爱", "nǐ yòng ài", "if you use love", "awak dengan kasih"],
    ["去细细擦拭", "qù xì xì cā shì", "to wipe it gently", "untuk mengelap dengan teliti"],
    ["，", "", "", ""],
    ["它就会", "tā jiù huì", "it will", "ia akan"],
    ["释放出", "shì fàng chū", "emit", "memancarkan"],
    ["永久的光泽", "yǒng jiǔ de guāng zé", "permanent luster", "kilauan yang kekal"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["有一次", "yǒu yí cì", "Once", "Suatu kali"],
    ["，", "", "", ""],
    ["爸爸让你", "bà ba ràng nǐ", "father asked you", "ayah suruh awak"],
    ["出去买醋", "chū qù mǎi cù", "to buy vinegar", "keluar beli cuka"],
    ["，", "", "", ""],
    ["本来", "běn lái", "originally", "asalnya"],
    ["给你", "gěi nǐ", "give you", "beri awak"],
    ["一个硬币", "yí gè yìng bì", "one coin", "satu syiling"],
    ["就够了", "jiù gòu le", "would be enough", "sudah cukup"],
    ["，", "", "", ""],
    ["但爸爸", "dàn bà ba", "but father", "tetapi ayah"],
    ["多给了你几个", "duō gěi le nǐ jǐ ge", "gave you a few extra", "beri awak lebih beberapa"],
    ["。", "", "", ""],
    ["爸爸发现", "bà ba fā xiàn", "Father discovered", "Ayah mendapati"],
    ["，", "", "", ""],
    ["你在出门的时候", "nǐ zài chū mén de shí hou", "when you went out", "ketika awak keluar"],
    ["，", "", "", ""],
    ["把多余的硬币", "bǎ duō yú de yìng bì", "the extra coins", "syiling yang lebih"],
    ["悄悄地", "qiāo qiāo de", "quietly", "secara senyap"],
    ["放在", "fàng zài", "placed on", "meletakkan di"],
    ["写字台的角上", "xiě zì tái de jiǎo shàng", "corner of the desk", "sudut meja tulis"],
    ["。", "", "", ""],
    ["那一刻", "nà yí kè", "At that moment", "Pada masa itu"],
    ["，", "", "", ""],
    ["爸爸", "bà ba", "father", "ayah"],
    ["装作没看见", "zhuāng zuò méi kàn jiàn", "pretended not to see", "berpura-pura tidak nampak"],
    ["，", "", "", ""],
    ["但你不知道", "dàn nǐ bù zhī dào", "but you don't know", "tetapi awak tidak tahu"],
    ["，", "", "", ""],
    ["爸爸的内心", "bà ba de nèi xīn", "father's heart", "hati ayah"],
    ["有多么高兴", "yǒu duō me gāo xìng", "how happy", "betapa gembiranya"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    ["孩子", "hái zi", "Child", "Anak"],
    ["，", "", "", ""],
    ["人生的", "rén shēng de", "Life's", "Hidup punya"],
    ["许多东西", "xǔ duō dōng xi", "many things", "banyak perkara"],
    ["是多余的", "shì duō yú de", "are superfluous", "adalah berlebihan"],
    ["，", "", "", ""],
    ["比如钱", "bǐ rú qián", "like money", "contohnya wang"],
    ["，", "", "", ""],
    ["比如欲望", "bǐ rú yù wàng", "like desire", "contohnya keinginan"],
    ["，", "", "", ""],
    ["比如名声", "bǐ rú míng shēng", "like fame", "contohnya nama"],
    ["。", "", "", ""],
    ["更多的时候", "gèng duō de shí hou", "Most of the time", "Lebih banyak masa"],
    ["，", "", "", ""],
    ["得到", "dé dào", "get", "dapat"],
    ["你该要的", "nǐ gāi yào de", "what you should have", "apa yang patut awak dapat"],
    ["该有的", "gāi yǒu de", "what you should have", "yang patut ada"],
    ["就够了", "jiù gòu le", "is enough", "sudah cukup"],
    ["，", "", "", ""],
    ["就像现在", "jiù xiàng xiàn zài", "just like now", "seperti sekarang"],
    ["，", "", "", ""],
    ["拿走", "ná zǒu", "take away", "ambil"],
    ["一个硬币", "yí gè yìng bì", "one coin", "satu syiling"],
    ["，", "", "", ""],
    ["剩下的", "shèng xià de", "the rest", "selebihnya"],
    ["，", "", "", ""],
    ["在你心里", "zài nǐ xīn lǐ", "in your heart", "dalam hati awak"],
    ["淡淡地扔掉", "dàn dàn de rēng diào", "lightly throw away", "buang dengan ringan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    ["爸爸想说的是", "bà ba xiǎng shuō de shì", "What father wants to say is", "Apa yang ayah mahu katakan"],
    ["，", "", "", ""],
    ["因为你的舍弃", "yīn wèi nǐ de shě qì", "because of your letting go", "kerana pelepasan awak"],
    ["，", "", "", ""],
    ["你豁然开阔的眼界里", "nǐ huò rán kāi kuò de yǎn jiè lǐ", "in your suddenly broadened vision", "dalam pandangan awak yang terbuka luas"],
    ["，", "", "", ""],
    ["将会发现", "jiāng huì fā xiàn", "you will discover", "akan menemui"],
    ["人生中", "rén shēng zhōng", "in life", "dalam hidup"],
    ["更多更美的", "gèng duō gèng měi de", "more and more beautiful", "lebih banyak dan lebih indah"],
    ["风景", "fēng jǐng", "scenery", "pemandangan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    ["爸爸在乡下", "bà ba zài xiāng xià", "Father in the countryside", "Ayah di kampung"],
    ["教书的那一年", "jiāo shū de nà yì nián", "the year he taught", "tahun mengajar"],
    ["，", "", "", ""],
    ["咱们家的日子", "zán men jiā de rì zi", "our family's life", "kehidupan keluarga kita"],
    ["过得很窘迫", "guò de hěn jiǒng pò", "was very difficult", "sangat susah"],
    ["，", "", "", ""],
    ["爸爸没有钱", "bà ba méi yǒu qián", "father had no money", "ayah tiada wang"],
    ["给你买玩具", "gěi nǐ mǎi wán jù", "to buy you toys", "untuk beli mainan awak"],
    ["，", "", "", ""],
    ["你找来", "nǐ zhǎo lái", "you found", "awak cari"],
    ["许多塑料袋", "xǔ duō sù liào dài", "many plastic bags", "banyak beg plastik"],
    ["，", "", "", ""],
    ["在一个塑料袋里", "zài yí gè sù liào dài lǐ", "in one plastic bag", "dalam satu beg plastik"],
    ["盛满水", "shèng mǎn shuǐ", "filled with water", "diisi penuh air"],
    ["，", "", "", ""],
    ["用针扎破了", "yòng zhēn zhā pò le", "poked a hole with a needle", "ditusuk dengan jarum"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["你看着", "nǐ kàn zhe", "you watched", "awak melihat"],
    ["细细的水流", "xì xì de shuǐ liú", "the thin stream of water", "aliran air yang halus"],
    ["流向", "liú xiàng", "flow to", "mengalir ke"],
    ["另一个袋子", "lìng yí gè dài zi", "another bag", "beg lain"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "and then", "kemudian"],
    ["，", "", "", ""],
    ["再换", "zài huàn", "change again", "tukar lagi"],
    ["另一个袋子", "lìng yí gè dài zi", "another bag", "beg lain"],
    ["，", "", "", ""],
    ["你玩得", "nǐ wán de", "you played", "awak bermain"],
    ["很快乐", "hěn kuài lè", "very happily", "dengan sangat gembira"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    ["或许", "huò xǔ", "Perhaps", "Mungkin"],
    ["，", "", "", ""],
    ["很小的时候", "hěn xiǎo de shí hou", "when you were very young", "semasa masih kecil"],
    ["，", "", "", ""],
    ["你就学会了", "nǐ jiù xué huì le", "you already learned", "awak sudah belajar"],
    ["在简单的生活中", "zài jiǎn dān de shēng huó zhōng", "in simple life", "dalam kehidupan yang sederhana"],
    ["寻找快乐", "xún zhǎo kuài lè", "to find happiness", "mencari kegembiraan"],
    ["。", "", "", ""],
    ["不错的", "bù cuò de", "That's right", "Betul"],
    ["，", "", "", ""],
    ["孩子", "hái zi", "child", "anak"],
    ["，", "", "", ""],
    ["生活中", "shēng huó zhōng", "in life", "dalam kehidupan"],
    ["有些东西", "yǒu xiē dōng xi", "some things", "sesetengah perkara"],
    ["并不容易改变", "bìng bù róng yì gǎi biàn", "are not easy to change", "tidak mudah berubah"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["容易改变的", "róng yì gǎi biàn de", "what is easy to change", "yang mudah berubah"],
    ["，", "", "", ""],
    ["是人的心情", "shì rén de xīn qíng", "is one's mood", "ialah perasaan manusia"],
    ["。", "", "", ""],
    ["孩子", "hái zi", "child", "anak"],
    ["，", "", "", ""],
    ["即便", "jí biàn", "even if", "walaupun"],
    ["你一生中", "nǐ yì shēng zhōng", "in your entire life", "sepanjang hidup awak"],
    ["什么也没有抓住", "shén me yě méi yǒu zhuā zhù", "you grasp nothing", "tiada apa yang awak capai"],
    ["，", "", "", ""],
    ["但抓住了快乐", "dàn zhuā zhù le kuài lè", "but you grasp happiness", "tetapi awak capai kegembiraan"],
    ["，", "", "", ""],
    ["你依旧", "nǐ yī jiù", "you are still", "awak masih"],
    ["是", "shì", "are", "ialah"],
    ["天底下", "tiān dǐ xià", "in the world", "di dunia"],
    ["最富有的人", "zuì fù yǒu de rén", "the richest person", "orang yang paling kaya"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    ["爸爸", "bà ba", "Father", "Ayah"],
    ["为你讲一个故事", "wèi nǐ jiǎng yí gè gù shì", "will tell you a story", "akan ceritakan sebuah cerita"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段

    ["你爷爷", "nǐ yé ye", "Your grandfather", "Datuk awak"],
    ["有一个朋友", "yǒu yí gè péng yǒu", "had a friend", "mempunyai seorang kawan"],
    ["是", "shì", "was", "ialah"],
    ["做大买卖的人", "zuò dà mǎi mài de rén", "a big businessman", "orang yang berniaga besar"],
    ["，", "", "", ""],
    ["有一年", "yǒu yì nián", "one year", "pada suatu tahun"],
    ["，", "", "", ""],
    ["他把", "tā bǎ", "he", "dia"],
    ["二十几个村庄的账", "èr shí jǐ ge cūn zhuāng de zhàng", "accounts from over twenty villages", "akaun dari lebih dua puluh kampung"],
    ["敛起来", "liǎn qǐ lái", "collected", "dikumpulkan"],
    ["，", "", "", ""],
    ["用纸包好了", "yòng zhǐ bāo hǎo le", "wrapped in paper", "dibungkus dengan kertas"],
    ["放在了咱家里", "fàng zài le zán jiā lǐ", "placed in our home", "diletakkan di rumah kita"],
    ["，", "", "", ""],
    ["他说", "tā shuō", "he said", "dia berkata"],
    ["他要到", "tā yào dào", "he was going to", "dia mahu pergi ke"],
    ["别的村子里去", "bié de cūn zi lǐ qù", "other villages", "kampung lain"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "lalu"],
    ["一拍屁股走了", "yì pāi pì gu zǒu le", "left without a second thought", "terus pergi"],
    ["。", "", "", ""],
    ["结果", "jié guǒ", "As a result", "Hasilnya"],
    ["，", "", "", ""],
    ["一连多少年", "yī lián duō shǎo nián", "for many years", "bertahun-tahun"],
    ["，", "", "", ""],
    ["再没有", "zài méi yǒu", "there was no more", "tiada lagi"],
    ["了他的消息", "le tā de xiāo xī", "news of him", "berita daripadanya"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第14段

    ["爸爸上学的时候", "bà ba shàng xué de shí hou", "When father was in school", "Ketika ayah bersekolah"],
    ["，", "", "", ""],
    ["你爷爷的肺病", "nǐ yé ye de fèi bìng", "your grandfather's lung disease", "penyakit paru-paru datuk awak"],
    ["已经很厉害了", "yǐ jīng hěn lì hài le", "was already very serious", "sudah sangat teruk"],
    ["，", "", "", ""],
    ["家里", "jiā lǐ", "at home", "di rumah"],
    ["一贫如洗", "yī pín rú xǐ", "extremely poor", "miskin papa"],
    ["。", "", "", ""],
    ["好几次", "hǎo jǐ cì", "Several times", "Beberapa kali"],
    ["，", "", "", ""],
    ["你奶奶", "nǐ nǎi nai", "your grandmother", "nenek awak"],
    ["提到", "tí dào", "mentioned", "menyebut"],
    ["那个账包的事情", "nà ge zhàng bāo de shì qing", "that money package", "bungkusan wang itu"],
    ["，", "", "", ""],
    ["你奶奶的意思", "nǐ nǎi nai de yì si", "your grandmother meant", "maksud nenek awak"],
    ["是", "shì", "was", "ialah"],
    ["挪用一下", "nuó yòng yí xià", "to use it temporarily", "menggunakan buat sementara"],
    ["，", "", "", ""],
    ["缓一缓", "huǎn yì huǎn", "to ease", "meringankan"],
    ["家里的紧张情况", "jiā lǐ de jǐn zhāng qíng kuàng", "the family's financial strain", "tekanan kewangan keluarga"],
    ["。", "", "", ""],
    ["你爷爷", "nǐ yé ye", "Your grandfather", "Datuk awak"],
    ["一瞪眼", "yī dèng yǎn", "glared", "merenung"],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["人家凭什么", "rén jiā píng shén me", "Why would he", "Kenapa dia"],
    ["敢把这么大的一笔钱", "gǎn bǎ zhè me dà de yī bǐ qián", "dare to leave such a large sum", "berani tinggalkan wang sebanyak ini"],
    ["放在咱这里", "fàng zài zán zhè lǐ", "with us", "di rumah kita"],
    ["，", "", "", ""],
    ["说明咱的人", "shuō míng zán de rén", "it shows our character", "menunjukkan peribadi kita"],
    ["比他的钱值钱", "bǐ tā de qián zhí qián", "is worth more than his money", "lebih berharga daripada wangnya"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第15段

    ["孩子", "hái zi", "Child", "Anak"],
    ["，", "", "", ""],
    ["你爷爷", "nǐ yé ye", "Your grandfather", "Datuk awak"],
    ["临死的时候", "lín sǐ de shí hou", "when he was dying", "ketika hampir mati"],
    ["，", "", "", ""],
    ["还是一个穷人", "hái shì yí gè qióng rén", "was still a poor man", "masih seorang yang miskin"],
    ["。", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["他", "tā", "he", "dia"],
    ["是", "shì", "was", "ialah"],
    ["一个响当当的穷人", "yí gè xiǎng dāng dāng de qióng rén", "a respectable poor man", "orang miskin yang terhormat"],
    ["。", "", "", ""],
    ["爸爸", "bà ba", "Father", "Ayah"],
    ["把这个故事", "bǎ zhè ge gù shì", "tell this story", "ceritakan cerita ini"],
    ["讲给你听", "jiǎng gěi nǐ tīng", "to you", "kepada awak"],
    ["，", "", "", ""],
    ["是希望", "shì xī wàng", "is to hope", "adalah berharap"],
    ["你能明白", "nǐ néng míng bái", "you can understand", "awak dapat faham"],
    ["，", "", "", ""],
    ["一个穷人", "yí gè qióng rén", "a poor man", "seorang miskin"],
    ["应该以怎样的风骨", "yīng gāi yǐ zěn yàng de fēng gǔ", "with what kind of integrity", "dengan maruah yang bagaimana"],
    ["，", "", "", ""],
    ["在这个世界上站立", "zài zhè ge shì jiè shàng zhàn lì", "should stand in this world", "harus berdiri di dunia ini"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["马德", "mǎ dé", "Ma De", "Ma De"],
    ["《", "", "", ""],
    ["一个父亲的箴言", "yí gè fù qīn de zhēn yán", "A Father's Admonition", "Nasihat Seorang Ayah"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
